### ISSUE TITLE
Can not use this theme.

### ISSUE THREAD

**Issue by zkerhcy** [hliu202/typora-purple-theme#1]
I install this theme as I follow the installation guide, just put the `Purple.css` file into the typora theme folder (on my mac it's `~/Library/Application Support/abnerworks.Typora/themes`), then I restart my typora app, but I can not find this theme from the Themes menu after the restart.

ENV:
- Typora version: 0.9.9.34.1 (4500)
- macOS version: 10.15.5

**Comment by hliu202** [comment]
> I install this theme as I follow the installation guide, just put the `Purple.css` file into the typora theme folder (on my mac it's `~/Library/Application Support/abnerworks.Typora/themes`), then I restart my typora app, but I can not find this theme from the Themes menu after the restart.
> 
> ENV:
> 
> * Typora version: 0.9.9.34.1 (4500)
> * macOS version: 10.15.5

Can you try again. There is some problem with capital Purple.css on MacOS. Now the css name is purple.css.
