### ISSUE TITLE
Table 的样式似乎有问题

### ISSUE THREAD

**Issue by heavenly-zy** [hliu202/typora-purple-theme#11]
这是 README 中的表格
![image](https://user-images.githubusercontent.com/50657815/101563875-08b10b00-3a05-11eb-9631-060bb9a0e3f1.png)

这是实际在 Typora 中显示出来的效果
![image](https://user-images.githubusercontent.com/50657815/101563954-2f6f4180-3a05-11eb-8be7-6e3d164a97b6.png)

**Comment by voidswordQQJ** [comment]
README 中的表格使用的是旧的表格样式，可以下载 v1.2.1 或之前的版本，或者修改 CSS 代码还原

**Comment by heavenly-zy** [comment]
> README 中的表格使用的是旧的表格样式，可以下载 v1.2.1 或之前的版本，或者修改 CSS 代码还原

这样哦，可我觉得旧的表格样式好看些，为啥要改啊

**Comment by hliu202** [comment]
你好，table样式现在少了边框，主要是想改的简洁点，
如果你喜欢原来的，可以把旧的css代码复制覆盖掉现在的

**Comment by heavenly-zy** [comment]
> 你好，table样式现在少了边框，主要是想改的简洁点，
> 如果你喜欢原来的，可以把旧的css代码复制覆盖掉现在的

嗯嗯，明白了

**Comment by voidswordQQJ** [comment]
> > 你好，table样式现在少了边框，主要是想改的简洁点，
> > 如果你喜欢原来的，可以把旧的css代码复制覆盖掉现在的
> 
> 嗯嗯，明白了

老哥是一直盯着回复吗 xD

**Comment by heavenly-zy** [comment]
> > > 你好，table样式现在少了边框，主要是想改的简洁点，
> > > 如果你喜欢原来的，可以把旧的css代码复制覆盖掉现在的
> > 
> > 
> > 嗯嗯，明白了
> 
> 老哥是一直盯着回复吗 xD

我这边貌似设置了邮件订阅，有回复就会邮件提醒我
