### ISSUE TITLE
主题显示空白

### ISSUE THREAD

**Issue by roxla** [hliu202/typora-purple-theme#24]
我把文件里面的purple.css文件复制到 C:\Users\1\AppData\Roaming\Typora\themes 主题文件夹下，重启 Typora 切换到该主题后只有空白的页面
![1](https://user-images.githubusercontent.com/28782384/132274620-42338497-7c9e-4653-9ec1-44824e382f9f.png)
Typora 版本 0.11.8
Typora 安装路径 D:\Program Files\Typora
系统版本 win10 19042.1165

**Comment by hliu202** [comment]
没法重现，你再确认一下：
1. 安装其他主题，看有没有问题？
2. 通过Typora->Preferences->Open Theme Folder，看看是不是copy到这个目录下了
