### ISSUE TITLE
**`** (backquote) 符号显示问题

### ISSUE THREAD

**Issue by HUGHNew** [hliu202/typora-purple-theme#26]
按下一个 \` 符号后 显示结果为
![image](https://user-images.githubusercontent.com/52786639/134649158-6d6c4762-8ac8-4377-99df-df2bbc888d1c.png) 
图中竖线为光标 实际符号有两个且光标在符号后
再按下一个 \` 后，显示结果为 
![image](https://user-images.githubusercontent.com/52786639/134649271-20395a3f-2c57-4489-947c-86a3bf5f56de.png)
输入等行为与预期正常，但显示结果有问题。此时，更换主题后显示结果为
![image](https://user-images.githubusercontent.com/52786639/134649440-3c866b00-6fd0-44b9-8e63-ebb03deecfc8.png)

猜测是主题在 line code 或者 block code相关css设置有一点问题

**Comment by hliu202** [comment]
1.5.4修复了
