### ISSUE TITLE
引用增强

### ISSUE THREAD

**Issue by you-hengh** [hliu202/typora-purple-theme#27]
很简单的修改,就不提交requests了
![image](https://user-images.githubusercontent.com/34816426/135601504-35be6e0d-83d4-4387-b310-1698abc53a73.png)
修改后展示:
![image](https://user-images.githubusercontent.com/34816426/135601541-53a3b45e-774d-46ba-a126-630595b7db8a.png)

**Comment by hliu202** [comment]
非常感谢，试了一下，感觉有点太醒目了，所以目前还是没有用这种样式
