### ISSUE TITLE
谢谢作者，想请教一个问题，关于purple里动漫人物没有显示的问题

### ISSUE THREAD

**Issue by Algo-Goer** [hliu202/typora-purple-theme#29]
作者您好，感谢分享这么好的作品！
不过我的Typora用了这个purple主题，写上内容后，动漫人物没有出现，其他purple颜色都在的。
如何显示动漫人物呢？谢谢！
@hliu202 @weijunfu

**Comment by caicc520** [comment]
我的也没出现

**Comment by voidswordQQJ** [comment]
那个是实列图，实际没有的，添加可以参考 #16

**Comment by hliu202** [comment]
可以`git checkout remotes/origin/test`，测试用的图片和md文本都在这个branch里
