### ISSUE TITLE
非常赞的紫色主题

### ISSUE THREAD

**Issue by Vinci-H** [hliu202/typora-purple-theme#3]
感谢开发者开发的这款紫色Markdown主题，最近半个月一直都有在使用。使用场景主要是在上课期间，用来记一些课堂笔记。使用过程中感觉存在一些看起来不太舒服的东西，比如：不同等级head的字体大小不好分辨等等。CSS代码我现在还看不懂，后面会去学习一下，然后来贡献一下，哈哈哈哈😄。

Email：1357997435@qq.com

**Comment by SunSeekerX** [comment]
太好看了，打印出来的pdf也好看
