### ISSUE TITLE
图片问题

### ISSUE THREAD

**Issue by mk-new-fish** [hliu202/typora-purple-theme#31]
楼主，您好~
看到您这个主题调的颜色，也太好看了把，想请教一下，这个图片是怎么弄上去的呀？可以分享一下吗？

**Comment by hliu202** [comment]
测试用的图片和md文本都在这个test branch: https://github.com/hliu202/typora-purple-theme/tree/test

**Comment by ShengXi2000** [comment]
我还以为为是主题自带的
