### ISSUE TITLE
在标题使用代码块时样式异常

### ISSUE THREAD

**Issue by ExplodingDragon** [hliu202/typora-purple-theme#34]
- 主题版本： v1.5.6 https://github.com/hliu202/typora-purple-theme/commit/807b041b1c81105e7fca91d90d5a62f8ba100ac4
- Typora 版本：Linux version 0.11.18(beta)

## 渲染图：
![image](https://user-images.githubusercontent.com/33776693/156685578-99b707c4-38f8-4f6a-a1ed-46747100c6b9.png)

## 内容：
![image](https://user-images.githubusercontent.com/33776693/156685649-2fe98431-4340-4b8f-8013-ec9219fd8517.png)

**Comment by hliu202** [comment]
Fixed
