### ISSUE TITLE
新版显示好像有点问题

### ISSUE THREAD

**Issue by SunSeekerX** [hliu202/typora-purple-theme#5]
![image](https://user-images.githubusercontent.com/48562733/97067279-5c4ecd00-15ee-11eb-80fd-646780ccc768.png)

1.0.0 版本的
![image](https://user-images.githubusercontent.com/48562733/97067299-9029f280-15ee-11eb-969f-bab83dcef2c3.png)

**Comment by hliu202** [comment]
哦，我把strong（就是粗体）改成了黑色，你喜欢原来的颜色的话，可以改回来。
就是感觉原来紫色太多，跟个人审美感觉有关，咋样都行
