### ISSUE TITLE
大神，请问有什么办法可以让引用块blockquote收缩和展开吗？

### ISSUE THREAD

**Issue by caiqiudan** [hliu202/typora-purple-theme#7]
大神，请问有什么办法可以让引用块blockquote收缩和展开吗？

**Comment by voidswordQQJ** [comment]
虽然没有弄过，不过这个类似的应该可以帮到你 [链接](https://www.jianshu.com/p/3f13850d66ea)

**Comment by caiqiudan** [comment]
感谢！请问可以在typroa里的html里写入latex公式吗？我希望latex公式可以利用html收缩展开。

**Comment by hliu202** [comment]
Sorry, 我也不清楚.
这只是个Typora主题,  关于Typora和Markdown的高端用法,  你还得去网上找找看看

**Comment by caiqiudan** [comment]
好的，非常感谢您分享的主题~
